[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd unified-backend && npm install"]

[phases.build]
cmds = ["cd unified-backend && npm run build"]

[start]
cmd = "cd unified-backend && npm start"