[build]
builder = "NIXPACKS"
buildCommand = "cd unified-backend && npm install && npm run build"
watchPatterns = ["unified-backend/**"]

[deploy]
startCommand = "cd unified-backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10